name: CI/CD Microservices

on:
  workflow_dispatch:        # Lancement manuel
  pull_request:             # PR
    branches: [ main ]      # Seulement vers main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPO_API: ds-api-gateway
  REPO_CLIENT: ds-client-service
  REPO_ACCOUNT: ds-account-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # (optionnel mais utile) voir l’architecture sur le runner
      - name: Show root files
        run: ls -la

      # 2) Installer Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3) Login DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # 4) Build + Push API Gateway
      - name: Build & Push API Gateway
        run: |
          cd $REPO_API
          mvn clean package -DskipTests
          docker build -t $DOCKERHUB_USERNAME/$REPO_API:latest .
          docker push $DOCKERHUB_USERNAME/$REPO_API:latest
          cd ..

      # 5) Build + Push Client Service
      - name: Build & Push Client Service
        run: |
          cd $REPO_CLIENT
          mvn clean package -DskipTests
          docker build -t $DOCKERHUB_USERNAME/$REPO_CLIENT:latest .
          docker push $DOCKERHUB_USERNAME/$REPO_CLIENT:latest
          cd ..

      # 6) Build + Push Account Service
      - name: Build & Push Account Service
        run: |
          cd $REPO_ACCOUNT
          mvn clean package -DskipTests
          docker build -t $DOCKERHUB_USERNAME/$REPO_ACCOUNT:latest .
          docker push $DOCKERHUB_USERNAME/$REPO_ACCOUNT:latest
          cd ..

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Simulate deployment
        run: echo "Simulating deployment of all services"
